name: lib-tests

on:
  pull_request:
    branches: [dev, main]
    paths:
      - 'lib/**'
      - '.github/workflows/test.yml'
  push:
    branches: [dev]
    paths:
      - 'lib/**'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lib
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: lib/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test --silent -- --run
